version: "3.2"

services:
  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    depends_on:
      - php
    ports:
      - 8099:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    links:
      - php

  php:
    container_name: agenda-php
    build:
      context: ./docker
    restart: always
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - ./:/var/www/html
      - /dev/shm:/dev/shm
